### ISSUE TITLE
Ganesha stability and using it for production

### ISSUE THREAD

**Issue by mouneshb** [ugoviti/izdock#2]
Hi,
https://hub.docker.com/r/izdock/nfs-ganesha made statement
"WARNING!!! WARNING!!! WARNING!!! NFS-GANESHA is NOT a production ready software! (at least 2018-09-21) It suffer from many and many bugs and stability issues. Never use it in production environment! Tested 2.3.x, 2.5.x, 2.6.x and 2.7.x relases, and all have many bugs, Segmentation Faults, lags, stuck problems, (NFS 4.0, 4.1 and 4.2), etc.. Use nfs-kernel instead if you don't want loose your time. WARNING!!! WARNING!!! WARNING!!!"

can you provide more details on what are tests suite you have to run to hit those issues.  ? are there any bugs raised against nfs-ganesha community, are these stability concern with nfs-4.x or even with nfs-3.x ?

**Comment by ugoviti** [comment]
Hi,
Right now I'm not using nfs-ganesha since 2018-09-21 and release 2.7.0
I tested nfs-ganesha inside Kubernetes cluster and experiencing continuous hard freezes, crash, data loss,  and slow down on data transfer (tested with versions 2.5.5, 2.6.3 and 2.7.0 for near 3 months).
I haven't any time to debug if instability is caused by Kubernetes Environment, anyway, switching back to nfs-kernel solved all stability issues (I'm using nfs server inside a container with 10/15 high traffic pods connected).

I'll test again the next major version of nfs-ganesha when released.

However, to be less catastrophic, I changed the README and removed the docker hub repo, so no one will use this repository.

Kind Regards
